### ISSUE TITLE
i2c for Fs management

### ISSUE THREAD

**Issue by vitsomeo** [AkiyukiOkayasu/GenericStereoAudioCodec#1]
Hello, Akiyuki.

Thank you for great driver. Is it possible to add i2c management in order to switch external clocking (BCK, LRCK), in similar way as HATs doing, like Hifiberry etc?

Thanks

**Comment by ndmgrphc** [comment]
If your dac chip has hardware mode can't you just control this manually?  I think adding i2c to this would make it no longer generic.  Maybe I misunderstood the point of this project.

**Comment by AkiyukiOkayasu** [comment]
Hi, sorry for the late reply.
This driver does not care about the ADC or DAC to connect. It simply sends and receives I2S.
If you want to configure the DAC via I2C, you can use pigpio.
This project may be useful for you.
https://github.com/AkiyukiOkayasu/AK4558_IOStream

**Comment by ndmgrphc** [comment]
Thanks for replying!  Just to clarify, this dto (AkiyukiOkayasu/RaspberryPi_I2S_Slave) would work for *any* DAC or ADC with 1) I2S support and 2) hardware control as long as there is some way to provide pi with a master CLK/LRCK.  Almost every ADC and DAC I see has some form of hardware control mode (not to mention master clock mode).  My understanding also was that a "linux sound driver" is simply a driver that complies with the linux sound control api and sends specific serial communication via I2C to whichever chip is supported.  For instance: [The PCM512x driver](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/sound/soc/codecs/pcm512x.c)

*edit: Also I assume this is why I see a lot of complaints in pi forums about "why is my audio playing back slow, not playing at all" etc -- as people are expecting i2c to magically take place.  All pi needs to know in slave mode is that it must honor the incoming clock/lr clock when sending PCM data to DOUT.  I hope I am understanding this correctly.

**Comment by AkiyukiOkayasu** [comment]
This is my first Linux device tree overlay and I'm not a Linux expert, but I think you're correct in your understanding.

Combining this device tree overlay with a hardware configuration (without I2C) of an ADC or DAC is a simple and prototyping-friendly method.
