### ISSUE TITLE
Support sampling rate

### ISSUE THREAD

**Issue by WuBillAJ** [AkiyukiOkayasu/GenericStereoAudioCodec#2]
Hi, i found that only work at PCM44.1K to PCM192K, would you plesae tell me how to change this feature? Higher sample rate and DSD suported is what i need, thanks

**Comment by AkiyukiOkayasu** [comment]
This project has not been maintained for many years, and to be honest, I don't remember much about it.

This device tree overlay is a user-friendly wrap around of the Linux "simple-audio-card", "linux,spdif-dit", and "linux,spdif-dir", but with a higher than 192kHz I imagine that the limitation is that sample rates higher than 192kHz cannot be used.

I have no experience with DSD equipment, but I2S is essentially a format that handles Linear-PCM, and I would think you would need to convert from DSD to Linear-PCM at some stage.
Whether that should be done in the application, in the device tree, or in the DAC, I don't know, but I think the easiest way is to do it in the application.

**Comment by AkiyukiOkayasu** [comment]
Probably not a limitation of "simple-audio-card".
It is probably a limitation of "linux,spdif-dit" and "linux,spdif-dir".
Please refer to this comment for more information about them.

https://github.com/AkiyukiOkayasu/RaspberryPi_I2S_Slave/blob/205e2f4a5e5a89052d853c4a3128e08eecaefa13/genericstereoaudiocodec.dts#L64-L69

https://github.com/AkiyukiOkayasu/RaspberryPi_I2S_Slave/blob/205e2f4a5e5a89052d853c4a3128e08eecaefa13/genericstereoaudiocodec.dts#L76-L81

**Comment by WuBillAJ** [comment]
Thank you so much for your instructions! "linux,spdif-dit" is the way that i can learn about how it work!
